### ISSUE TITLE
Add a "content" option

### ISSUE THREAD

**Issue by TheUntraceable** [HisRoyalBaguettes/clever-chat-v7#5]
As you made your API with a load of options, getting into favourite actors (that's pretty nice), you could add a "content" option where you can supply what the bot said to use as context. This would be really really nice for a cache system to make your code run way faster. This would remove the need for making an API call, every single time someone gets lonely and needs a friend to talk to.
The cache would look like
 ```JSON
{"What_Human_Said" : "What_Bot_Replied_With"}
```
Other than that, API looks great and I'll use it as a subsitute.

**Comment by hisRoyalty** [comment]
Would implement that soon.

**Comment by hisRoyalty** [comment]
@TheUntraceable hello,
It's been a while since the package was updated, and it's sinking deep. Now I really don't understand what's with this as an issue.
You are using this as a discord bot. May you please explain me what's the use of this? The package is pretty dead and 'abandoned' so I don't really see the use of doing it.

**Comment by hisRoyalty** [comment]
clever-chat is officially discontinued as of November 2022.
